--[[
  Copyright (C) 2025 Rotorflight Project
  GPLv3 — https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    [5] = "pitch rate",
    [6] = "roll rate",
    [7] = "yaw rate",
    [8] = "pitch rc rate",
    [9] = "roll rc rate",
    [10] = "yaw rc rate",
    [11] = "pitch rc expo",
    [12] = "roll rc expo",
    [13] = "yaw rc expo",
    [14] = "pitch p gain",
    [15] = "pitch i gain",
    [16] = "pitch d gain",
    [17] = "pitch f gain",
    [18] = "roll p gain",
    [19] = "roll i gain",
    [20] = "roll d gain",
    [21] = "roll f gain",
    [22] = "yaw p gain",
    [23] = "yaw i gain",
    [24] = "yaw d gain",
    [25] = "yaw f gain",
    [26] = "yaw cw gain",
    [27] = "yaw ccw gain",
    [28] = "yaw cyclic ff",
    [29] = "yaw collective ff",
    [30] = "yaw collective dyn",
    [31] = "yaw collective decay",
    [32] = "pitch collective ff",
    [33] = "pitch gyro cutoff",
    [34] = "roll gyro cutoff",
    [35] = "yaw gyro cutoff",
    [36] = "pitch dterm cutoff",
    [37] = "roll dterm cutoff",
    [38] = "yaw dterm cutoff",
    [39] = "rescue climb collective",
    [40] = "rescue hover collective",
    [41] = "rescue hover alt",
    [42] = "rescue alt p gain",
    [43] = "rescue alt i gain",
    [44] = "rescue alt d gain",
    [45] = "angle level gain",
    [46] = "horizon level gain",
    [47] = "acro gain",
    [48] = "gov gain",
    [49] = "gov p gain",
    [50] = "gov i gain",
    [51] = "gov d gain",
    [52] = "gov f gain",
    [53] = "gov tta gain",
    [54] = "gov cyclic ff",
    [55] = "gov collective ff",
    [56] = "pitch b gain",
    [57] = "roll b gain",
    [58] = "yaw b gain",
    [59] = "pitch o gain",
    [60] = "roll o gain",
    [61] = "crossc gain",
    [62] = "crossc ratio",
    [63] = "crossc cutoff",
    [64] = "acc pitch trim",
    [65] = "acc roll trim",
    [66] = "yaw inertia precomp gain",
    [67] = "yaw inertia precomp cutoff",
    [68] = "pitch setpoint boost gain",
    [69] = "roll setpoint boost gain",
    [70] = "yaw setpoint boost gain",
    [71] = "collective setpoint boost gain",
    [72] = "yaw dyn ceiling gain",
    [73] = "yaw dyn deadband gain",
    [74] = "yaw dyn deadband filter",
    [75] = "yaw precomp cutoff",
}
