--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["esc_signature"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_signature)@",
    ["esc_command"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_command)@",
    ["esc_type"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_type)@",
    ["esc_model"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_model)@",
    ["esc_sn"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_sn)@",
    ["esc_iap"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_iap)@",
    ["esc_fw"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_fw)@",
    ["esc_hardware"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_hardware)@",
    ["throttle_min"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.throttle_min)@",
    ["throttle_max"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.throttle_max)@",
    ["esc_mode"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.governor)@",
    ["cell_count"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.cell_count)@",
    ["low_voltage_protection"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.low_voltage_protection)@",
    ["temperature_protection"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.temperature_protection)@",
    ["bec_voltage"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.bec_voltage)@",
    ["electrical_angle"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.electrical_angle)@",
    ["motor_direction"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_direction)@",
    ["starting_torque"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.starting_torque)@",
    ["response_speed"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.response_speed)@",
    ["buzzer_volume"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.buzzer_volume)@",
    ["current_gain"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.current_gain)@",
    ["fan_control"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.fan_control)@",
    ["soft_start"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.soft_start)@",
    ["auto_restart_time"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.auto_restart_time)@",
    ["restart_acc"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.restart_acc)@",
    ["gov_p"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.gov_p)@",
    ["gov_i"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.gov_i)@",
    ["active_freewheel"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.active_freewheel)@",
    ["drive_freq"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.drive_freq)@",
    ["motor_erpm_max"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_erpm_max)@",
    ["throttle_protocol"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.throttle_protocol)@",
    ["telemetry_protocol"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.telemetry_protocol)@",
    ["led_color_index"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.led_color_index)@",
    ["led_color_rgb"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.led_color_rgb)@",
    ["motor_temp_sensor"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_temp_sensor)@",
    ["motor_temp"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_temp)@",
    ["battery_capacity"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.battery_capacity)@",
}
