--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["esc_signature"] = "@i18n(api.ESC_PARAMETERS_SCORPION.esc_signature)@",
    ["esc_command"] = "@i18n(api.ESC_PARAMETERS_SCORPION.esc_command)@",
    ["escinfo_1"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_1)@",
    ["escinfo_2"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_2)@",
    ["escinfo_3"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_3)@",
    ["escinfo_4"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_4)@",
    ["escinfo_5"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_5)@",
    ["escinfo_6"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_6)@",
    ["escinfo_7"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_7)@",
    ["escinfo_8"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_8)@",
    ["escinfo_9"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_9)@",
    ["escinfo_10"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_10)@",
    ["escinfo_11"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_11)@",
    ["escinfo_12"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_12)@",
    ["escinfo_13"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_13)@",
    ["escinfo_14"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_14)@",
    ["escinfo_15"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_15)@",
    ["escinfo_16"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_16)@",
    ["escinfo_17"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_17)@",
    ["escinfo_18"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_18)@",
    ["escinfo_19"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_19)@",
    ["escinfo_20"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_20)@",
    ["escinfo_21"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_21)@",
    ["escinfo_22"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_22)@",
    ["escinfo_23"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_23)@",
    ["escinfo_24"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_24)@",
    ["escinfo_25"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_25)@",
    ["escinfo_26"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_26)@",
    ["escinfo_27"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_27)@",
    ["escinfo_28"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_28)@",
    ["escinfo_29"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_29)@",
    ["escinfo_30"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_30)@",
    ["escinfo_31"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_31)@",
    ["escinfo_32"] = "@i18n(api.ESC_PARAMETERS_SCORPION.escinfo_32)@",
    ["esc_mode"] = "@i18n(api.ESC_PARAMETERS_SCORPION.esc_mode)@",
    ["bec_voltage"] = "@i18n(api.ESC_PARAMETERS_SCORPION.bec_voltage)@",
    ["rotation"] = "@i18n(api.ESC_PARAMETERS_SCORPION.rotation)@",
    ["telemetry_protocol"] = "@i18n(api.ESC_PARAMETERS_SCORPION.telemetry_protocol)@",
    ["protection_delay"] = "@i18n(api.ESC_PARAMETERS_SCORPION.protection_delay)@",
    ["min_voltage"] = "@i18n(api.ESC_PARAMETERS_SCORPION.min_voltage)@",
    ["max_temperature"] = "@i18n(api.ESC_PARAMETERS_SCORPION.max_temperature)@",
    ["max_current"] = "@i18n(api.ESC_PARAMETERS_SCORPION.max_current)@",
    ["cutoff_handling"] = "@i18n(api.ESC_PARAMETERS_SCORPION.cutoff_handling)@",
    ["max_used"] = "@i18n(api.ESC_PARAMETERS_SCORPION.max_used)@",
    ["motor_startup_sound"] = "@i18n(api.ESC_PARAMETERS_SCORPION.motor_startup_sound)@",
    ["padding_1"] = "@i18n(api.ESC_PARAMETERS_SCORPION.padding_1)@",
    ["padding_2"] = "@i18n(api.ESC_PARAMETERS_SCORPION.padding_2)@",
    ["padding_3"] = "@i18n(api.ESC_PARAMETERS_SCORPION.padding_3)@",
    ["soft_start_time"] = "@i18n(api.ESC_PARAMETERS_SCORPION.soft_start_time)@",
    ["runup_time"] = "@i18n(api.ESC_PARAMETERS_SCORPION.runup_time)@",
    ["bailout"] = "@i18n(api.ESC_PARAMETERS_SCORPION.bailout)@",
    ["gov_proportional"] = "@i18n(api.ESC_PARAMETERS_SCORPION.gov_proportional)@",
    ["gov_integral"] = "@i18n(api.ESC_PARAMETERS_SCORPION.gov_integral)@",
}
