--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["pid_mode"] = "@i18n(api.PID_PROFILE.pid_mode)@",
    ["error_decay_time_ground"] = "@i18n(api.PID_PROFILE.error_decay_time_ground)@",
    ["error_decay_time_cyclic"] = "@i18n(api.PID_PROFILE.error_decay_time_cyclic)@",
    ["error_decay_time_yaw"] = "@i18n(api.PID_PROFILE.error_decay_time_yaw)@",
    ["error_decay_limit_cyclic"] = "@i18n(api.PID_PROFILE.error_decay_limit_cyclic)@",
    ["error_decay_limit_yaw"] = "@i18n(api.PID_PROFILE.error_decay_limit_yaw)@",
    ["error_rotation"] = "@i18n(api.PID_PROFILE.error_rotation)@",
    ["error_limit_0"] = "@i18n(api.PID_PROFILE.error_limit_0)@",
    ["error_limit_1"] = "@i18n(api.PID_PROFILE.error_limit_1)@",
    ["error_limit_2"] = "@i18n(api.PID_PROFILE.error_limit_2)@",
    ["gyro_cutoff_0"] = "@i18n(api.PID_PROFILE.gyro_cutoff_0)@",
    ["gyro_cutoff_1"] = "@i18n(api.PID_PROFILE.gyro_cutoff_1)@",
    ["gyro_cutoff_2"] = "@i18n(api.PID_PROFILE.gyro_cutoff_2)@",
    ["dterm_cutoff_0"] = "@i18n(api.PID_PROFILE.dterm_cutoff_0)@",
    ["dterm_cutoff_1"] = "@i18n(api.PID_PROFILE.dterm_cutoff_1)@",
    ["dterm_cutoff_2"] = "@i18n(api.PID_PROFILE.dterm_cutoff_2)@",
    ["iterm_relax_type"] = "@i18n(api.PID_PROFILE.iterm_relax_type)@",
    ["iterm_relax_cutoff_0"] = "@i18n(api.PID_PROFILE.iterm_relax_cutoff_0)@",
    ["iterm_relax_cutoff_1"] = "@i18n(api.PID_PROFILE.iterm_relax_cutoff_1)@",
    ["iterm_relax_cutoff_2"] = "@i18n(api.PID_PROFILE.iterm_relax_cutoff_2)@",
    ["yaw_cw_stop_gain"] = "@i18n(api.PID_PROFILE.yaw_cw_stop_gain)@",
    ["yaw_ccw_stop_gain"] = "@i18n(api.PID_PROFILE.yaw_ccw_stop_gain)@",
    ["yaw_precomp_cutoff"] = "@i18n(api.PID_PROFILE.yaw_precomp_cutoff)@",
    ["yaw_cyclic_ff_gain"] = "@i18n(api.PID_PROFILE.yaw_cyclic_ff_gain)@",
    ["yaw_collective_ff_gain"] = "@i18n(api.PID_PROFILE.yaw_collective_ff_gain)@",
    ["yaw_collective_dynamic_gain"] = "@i18n(api.PID_PROFILE.yaw_collective_dynamic_gain)@",
    ["yaw_collective_dynamic_decay"] = "@i18n(api.PID_PROFILE.yaw_collective_dynamic_decay)@",
    ["pitch_collective_ff_gain"] = "@i18n(api.PID_PROFILE.pitch_collective_ff_gain)@",
    ["angle_level_strength"] = "@i18n(api.PID_PROFILE.angle_level_strength)@",
    ["angle_level_limit"] = "@i18n(api.PID_PROFILE.angle_level_limit)@",
    ["horizon_level_strength"] = "@i18n(api.PID_PROFILE.horizon_level_strength)@",
    ["trainer_gain"] = "@i18n(api.PID_PROFILE.trainer_gain)@",
    ["trainer_angle_limit"] = "@i18n(api.PID_PROFILE.trainer_angle_limit)@",
    ["cyclic_cross_coupling_gain"] = "@i18n(api.PID_PROFILE.cyclic_cross_coupling_gain)@",
    ["cyclic_cross_coupling_ratio"] = "@i18n(api.PID_PROFILE.cyclic_cross_coupling_ratio)@",
    ["cyclic_cross_coupling_cutoff"] = "@i18n(api.PID_PROFILE.cyclic_cross_coupling_cutoff)@",
    ["offset_limit_0"] = "@i18n(api.PID_PROFILE.offset_limit_0)@",
    ["offset_limit_1"] = "@i18n(api.PID_PROFILE.offset_limit_1)@",
    ["bterm_cutoff_0"] = "@i18n(api.PID_PROFILE.bterm_cutoff_0)@",
    ["bterm_cutoff_1"] = "@i18n(api.PID_PROFILE.bterm_cutoff_1)@",
    ["bterm_cutoff_2"] = "@i18n(api.PID_PROFILE.bterm_cutoff_2)@",
    ["yaw_inertia_precomp_gain"] = "@i18n(api.PID_PROFILE.yaw_inertia_precomp_gain)@",
    ["yaw_inertia_precomp_cutoff"] = "@i18n(api.PID_PROFILE.yaw_inertia_precomp_cutoff)@",
}
