--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["telemetry_inverted"] = "@i18n(api.TELEMETRY_CONFIG.telemetry_inverted)@",
    ["halfDuplex"] = "@i18n(api.TELEMETRY_CONFIG.halfDuplex)@",
    ["enableSensors"] = "@i18n(api.TELEMETRY_CONFIG.enableSensors)@",
    ["pinSwap"] = "@i18n(api.TELEMETRY_CONFIG.pinSwap)@",
    ["crsf_telemetry_mode"] = "@i18n(api.TELEMETRY_CONFIG.crsf_telemetry_mode)@",
    ["crsf_telemetry_link_rate"] = "@i18n(api.TELEMETRY_CONFIG.crsf_telemetry_link_rate)@",
    ["crsf_telemetry_link_ratio"] = "@i18n(api.TELEMETRY_CONFIG.crsf_telemetry_link_ratio)@",
    ["telem_sensor_slot_1"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_1)@",
    ["telem_sensor_slot_2"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_2)@",
    ["telem_sensor_slot_3"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_3)@",
    ["telem_sensor_slot_4"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_4)@",
    ["telem_sensor_slot_5"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_5)@",
    ["telem_sensor_slot_6"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_6)@",
    ["telem_sensor_slot_7"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_7)@",
    ["telem_sensor_slot_8"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_8)@",
    ["telem_sensor_slot_9"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_9)@",
    ["telem_sensor_slot_10"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_10)@",
    ["telem_sensor_slot_11"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_11)@",
    ["telem_sensor_slot_12"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_12)@",
    ["telem_sensor_slot_13"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_13)@",
    ["telem_sensor_slot_14"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_14)@",
    ["telem_sensor_slot_15"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_15)@",
    ["telem_sensor_slot_16"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_16)@",
    ["telem_sensor_slot_17"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_17)@",
    ["telem_sensor_slot_18"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_18)@",
    ["telem_sensor_slot_19"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_19)@",
    ["telem_sensor_slot_20"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_20)@",
    ["telem_sensor_slot_21"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_21)@",
    ["telem_sensor_slot_22"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_22)@",
    ["telem_sensor_slot_23"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_23)@",
    ["telem_sensor_slot_24"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_24)@",
    ["telem_sensor_slot_25"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_25)@",
    ["telem_sensor_slot_26"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_26)@",
    ["telem_sensor_slot_27"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_27)@",
    ["telem_sensor_slot_28"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_28)@",
    ["telem_sensor_slot_29"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_29)@",
    ["telem_sensor_slot_30"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_30)@",
    ["telem_sensor_slot_31"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_31)@",
    ["telem_sensor_slot_32"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_32)@",
    ["telem_sensor_slot_33"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_33)@",
    ["telem_sensor_slot_34"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_34)@",
    ["telem_sensor_slot_35"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_35)@",
    ["telem_sensor_slot_36"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_36)@",
    ["telem_sensor_slot_37"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_37)@",
    ["telem_sensor_slot_38"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_38)@",
    ["telem_sensor_slot_39"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_39)@",
    ["telem_sensor_slot_40"] = "@i18n(api.TELEMETRY_CONFIG.telem_sensor_slot_40)@",
}
